### ISSUE TITLE
Can't build with the latest DMD (2.067.1)

### ISSUE THREAD

**Issue by whitebyte** [jzhu98/star-entity#7]
Subj. "dub build" spits this:
```
source/star/entity/entity.d(70): Error: undefined identifier 'conv'
```
It seems that std.conv isn't imported for some reason. Adding 
```
import std.conv : to;
```
at the beginning of entity.d seems to solve the issue, hovewer I'm not sure that this is an optimal way, so I don't make a PR for now.

**Comment by cschram** [comment]
This should be closed, since it was fixed in [2d3ec4c](https://github.com/jzhu98/star-entity/commit/2d3ec4cc525c5137469a5f0271b3b1cbbb3d5579).
